#Parameters
parameters:
    data: ['copula'] # 'gwas,copula
    n_sample: 10000
    n_covariates: 15
    model: 'm3e2' #MMoE or MMoEEx (MAML)
    id: 'config2_testing' #description
    suffle: True
    best_validation_test: True
    batch_size: 100
    max_epochs: 100
    print: 30
    decay: 20
    alpha: 0.01 #decay downgrad
    gamma: 0.9 #Adam decay
    lr: 0.0001 #learning rate
    wd: 0.001 #decay
    dropoutp: 0.25
    pos_weight_y: 0.7
    pos_weight: [1, 1, 1,1]
    num_exp: 2
    units_exp: 4
    hidden1: 6
    hidden2: 3
    type_treatment: 'continuous' #continuous, binary
    type_target: 'binary'
    baselines: True
    baselines_list: ['DA']
    loss_target: 5
    loss_da: 1
    loss_treat: 3
    loss_reg: 1