#Parameters
parameters:
    data: ['gwas'] #gwas, copula
    n_sample: 1000
    n_covariates: 995
    n_treatments: 5
    model: 'm3e2'
    id: 'config1_testing'
    suffle: True
    best_validation_test: True
    batch_size: 50
    max_epochs: 150
    print: 15
    decay: 20
    alpha: 0.0001 #decay downgrad
    gamma: 0.9 #Adam decay
    lr: 0.001 #learning rate
    wd: 0.001 #weight_decay
    dropoutp: 0.25
    pos_weight_y: 1.25
    num_exp: 2
    units_exp: 4
    hidden1: 64
    hidden2: 8
    type_treatment: 'binary' #continuous, binary
    type_target: 'binary' #continuous, binary
    baselines: False
    baselines_list: ['DA','CEVAE']
    loss_target: 5
    loss_da: 10
    loss_treat: 1
    loss_reg: 1
