#Parameters
parameters:
    data: ['copula'] # 'gwas,copula
    n_sample: 10000
    n_covariates: 15
    model: 'm3e2' #MMoE or MMoEEx (MAML)
    id: 'config2_testing' #description
    suffle: True
    best_validation_test: True
    batch_size: 100
    max_epochs: 100
    print: 50
    decay: 20
    alpha: 0.01 #decay downgrad
    gamma: 0.9 #Adam decay
    lr: 0.001 #learning rate
    wd: 0.01 #decay
    dropoutp: 0.25
    pos_weight_y: 1.2
    pos_weights: 9
    num_exp: 2
    units_exp: 4
    hidden1: 6
    hidden2: 3
    type_treatment: 'continuous' #continuous, binary
    type_target: 'binary'
    baselines: False
    baselines_list: ['DA']
    loss_target: 3
    loss_da: 3
    loss_treat: 1
    loss_reg: 1