#Parameters
parameters:
    data: ['ihdp'] #gwas, copula
    model: 'm3e2'
    n_treatments: 1
    id: 'config3a'
    suffle: True
    best_validation_test: True
    batch_size: 20
    max_epochs: 100
    print: 25
    decay: 20
    alpha: 0.01
    gamma: 0.8 #Adam decay
    lr: 0.1 #learning rate 0.001
    wd: 0.05 #weight_decay
    dropoutp: 0.5
    pos_weights: 5
    num_exp: 2
    units_exp: 4
    hidden1: 16
    hidden2: 8
    type_treatment: 'binary' #continuous, binary
    type_target: 'continuous' #continuous, binary
    baselines: True
    baselines_list: ['DA','Dragonnet','CEVAE']#,,
    loss_target: 6
    loss_da: 5
    loss_treat: 4
    loss_reg: 1

