#Parameters
parameters:
    data: ['copula'] #gwas, copula
    n_sample: 100
    n_covariates: 2000
    n_treatments: 4
    model: 'm3e2'
    id: 'config2k'
    suffle: True
    best_validation_test: True
    batch_size: 500
    max_epochs: 200
    print: 100
    decay: 40
    alpha: 0.0001 #decay downgrad
    gamma: 0.9 #Adam decay
    lr: 0.001 #learning rate
    wd: 0.005 #weight_decay
    dropoutp: 0.25
    pos_weight_y: 1.25
    num_exp: 2
    units_exp: 4
    hidden1: 64
    hidden2: 8
    type_treatment: 'binary' #continuous, binary
    type_target: 'binary' #continuous, binary
    baselines: True
    baselines_list: ['DA','CEVAE']