#Parameters
parameters:
    data: ['gwas'] #gwas, copula
    n_sample: 10000
    n_covariates: 1000
    n_treatments: 3
    model: 'm3e2'
    id: 'config1e'
    suffle: True
    best_validation_test: True
    batch_size: 100
    max_epochs: 100
    print: 50
    decay: 20
    alpha: 0.01 #decay downgrad
    gamma: 0.8 #Adam decay
    lr: 0.001 #learning rate
    wd: 0.05 #weight_decay
    dropoutp: 0.5
    pos_weight_y: 1
    pos_weights: 9
    num_exp: 4
    units_exp: 4
    hidden1: 64
    hidden2: 8
    type_treatment: 'binary' #continuous, binary
    type_target: 'binary' #continuous, binary
    baselines: True
    baselines_list: ['DA','CEVAE']
    loss_target: 3
    loss_da: 3
    loss_treat: 1
    loss_reg: 1